### ISSUE TITLE
Publication to introduce the package

### ISSUE THREAD

**Issue by Shicheng-Guo** [AstraZeneca/Omicsfold#4]
Dear Stuart McHattie, Stefano Borini, Khader Shameer, 

Is there any publication to introduce Omicsfold package? 

Thanks.

Shicheng

**Comment by vgopalakrishnan1** [comment]
Hi Shicheng,

Apologies for the late reply. We are working on the publication and are hoping to submit for peer review shortly. Here is a link to a conference publication on OmicsFold. https://onlinelibrary.wiley.com/doi/full/10.1002/lrh2.10300. @shameer
